# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c61deab3ebb89f58f3c71702bb0deb68dae8d92d45d43309feea45e06a818d83ed40e0dce68c888aa0f128c14d3581bcc8af9870db1581dc4d0324b1e959843

test:
  secret_key_base: aed71ffa5837ba19fdbb247790dfad0fd971cccc087969acb8e8fd248e215c1aecf8e70cc07a764a848962894fc13c8c36daba43227efc1221c2fb843b4aa087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
